["minecraft:apple"]
# tbd, maybe latent speed for fruit

["minecraft:baked_potato"]
"minecraft:resistance"=0

["minecraft:beetroot"]
# latent strength

["minecraft:beetroot_soup"]
"minecraft:strength"=2 # triangular root of six beets

["minecraft:bread"]
# none - the generic food

# cake needs handling as a special case

["minecraft:carrot"]
# latent night vision

["minecraft:chorus_fruit"]

["minecraft:cooked_chicken"]
"minecraft:slow_falling"=0

["minecraft:cooked_cod"]
# tbd

["minecraft:cooked_mutton"]
# tbd

["minecraft:cooked_porkchop"]
# tbd

["minecraft:cooked_rabbit"]
"minecraft:jump_boost"=0

["minecraft:cooked_salmon"]
# tbd

["minecraft:cookie"]
# tbd

["minecraft:dried_kelp"]
"minecraft:water_breathing"=0

["minecraft:enchanted_golden_apple"]
# kinda does its own thing

["minecraft:golden_apple"]
# ditto

["minecraft:glow_berries"]
"minecraft:glowing"=0

["minecraft:golden_carrot"]
"minecraft:night_vision"=0

["minecraft:honey_bottle"]
# is this actually food?
"minecraft:speed"=0

["minecraft:melon_slice"]
# tbd

["minecraft:mushroom_stew"]
"minecraft:haste"=1 # two mushrooms

["minecraft:poisonous_potato"]
# tbd, does its own thing

["minecraft:potato"]
# latent resistance

["minecraft:pufferfish"]
# does its own thing

["minecraft:pumpkin_pie"]
"minecraft:invisibility"=0 # pumpkin
"minecraft:speed"=0 # sugar
# egg effect tbd

["minecraft:rabbit_stew"]
"minecraft:jump_boost"=1
"minecraft:haste"=0
"minecraft:night_vision"=0
"minecraft:resistance"=1

["minecraft:raw_beef"]
# latent strength

["minecraft:raw_chicken"]
# latent slow falling

["minecraft:raw_cod"]
# tbd

["minecraft:raw_mutton"]
# tbd

["minecraft:raw_porkchop"]
# tbd

["minecraft:raw_rabbit"]
# latent jump boost

["minecraft:raw_salmon"]
# tbd

["minecraft:rotten_flesh"]
# tbd

["minecraft:spider_eye"]
# does its own thing but could be more interesting

["minecraft:cooked_beef"]
"minecraft:strength"=0

["minecraft:suspicious_stew"]
"minecraft:haste"=1 # two mushrooms
# also does its own thing

["minecraft:sweet_berries"]
# tbd

["minecraft:tropical_fish"]
"minecraft:dolphins_grace"=0



